"""created one to many relationship between board and card

Revision ID: 15be20887666
Revises: da492c7153b8
Create Date: 2022-06-28 16:40:10.515220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15be20887666'
down_revision = 'da492c7153b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'card', 'card', ['board_id'], ['card_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'board_id')
    # ### end Alembic commands ###
