"""updated Card model foreign key

Revision ID: aa222dc11b71
Revises: 15be20887666
Create Date: 2022-06-28 20:04:34.257759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa222dc11b71'
down_revision = '15be20887666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('card_board_id_fkey', 'card', type_='foreignkey')
    op.create_foreign_key(None, 'card', 'board', ['board_id'], ['board_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.create_foreign_key('card_board_id_fkey', 'card', 'card', ['board_id'], ['card_id'])
    # ### end Alembic commands ###
